AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: async-backend SAM template for the ID Check v2 app

Parameters:
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - dev
      - build
      - staging
    Default: dev

  CodeSigningConfigArn:
    Description: |
      The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Type: String
    Default: none

  PermissionsBoundary:
    Description: |
      The ARN of the permissions boundary to apply to any role created by the template
    Type: String
    Default: none

  DevOverrideStsBaseUrl:
    Description: |
      Override the STS_BASE_URL value for development deployments
    Type: String
    Default: none

  DeployAlarmsInDev:
    Description: Set to `true` to deploy alarms in a dev environment
    Type: String
    Default: false

Mappings:
  StaticVariables:
    urls:
      WarningAlarmsRunbook: https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/4800446694/Alarms+Runbook+Warnings
      CriticalAlarmsRunbook: https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/4799594677/Alarms+Runbook+Alerts
  EnvironmentConfiguration:
    dev:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
    build:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
    staging:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
    integration:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceNonProductionVariables
    production:
      dynatraceSecretArn: arn:aws:secretsmanager:eu-west-2:216552277552:secret:DynatraceProductionVariables

  PrivateApigw:
    dev:
      ApiBurstLimit: 10
      ApiRateLimit: 10
      IpvCoreVpceId: ""
    build:
      ApiBurstLimit: 10
      ApiRateLimit: 10
      IpvCoreVpceId: ""
    staging:
      ApiBurstLimit: 10
      ApiRateLimit: 10
      IpvCoreVpceId: "vpce-0555f751a645d7639"
    integration:
      ApiBurstLimit: 0
      ApiRateLimit: 0
      IpvCoreVpceId: ""
    production:
      ApiBurstLimit: 0
      ApiRateLimit: 0
      IpvCoreVpceId: ""

  SessionsApigw:
    dev:
      ApiBurstLimit: 10
      ApiRateLimit: 10
    build:
      ApiBurstLimit: 10
      ApiRateLimit: 10
    staging:
      ApiBurstLimit: 10
      ApiRateLimit: 10
    integration:
      ApiBurstLimit: 0
      ApiRateLimit: 0
    production:
      ApiBurstLimit: 0
      ApiRateLimit: 0

  ProxyApigw:
    dev:
      ApiBurstLimit: 10
      ApiRateLimit: 10
    build:
      ApiBurstLimit: 10
      ApiRateLimit: 10
    staging:
      ApiBurstLimit: 10
      ApiRateLimit: 10
    integration:
      ApiBurstLimit: 0
      ApiRateLimit: 0
    production:
      ApiBurstLimit: 0
      ApiRateLimit: 0

  Lambda:
    dev:
      ReservedConcurrentExecutions: 0 # Placeholder value to satisfy Cloudformation validation requirements when the environment is dev
      LogLevel: DEBUG
    build:
      ReservedConcurrentExecutions: 15
      LogLevel: INFO
    staging:
      ReservedConcurrentExecutions: 15
      LogLevel: INFO
    integration:
      ReservedConcurrentExecutions: 0
      LogLevel: INFO
    production:
      ReservedConcurrentExecutions: 0
      LogLevel: INFO

  TxMA:
    dev:
      TxmaAccount: arn:aws:iam::248098332657:root
    build:
      TxmaAccount: arn:aws:iam::750703655225:root
    staging:
      TxmaAccount: arn:aws:iam::178023842775:root
    integration:
      TxmaAccount: arn:aws:iam::729485541398:root
    production:
      TxmaAccount: arn:aws:iam::451773080033:root

  KMS:
    dev:
      PendingDeletionInDays: 7
    build:
      PendingDeletionInDays: 30
    staging:
      PendingDeletionInDays: 30
    integration:
      PendingDeletionInDays: 30
    production:
      PendingDeletionInDays: 30

  DNS:
    dev:
      BaseDns: review-b-async.dev.account.gov.uk
    build:
      BaseDns: review-b-async.build.account.gov.uk
    staging:
      BaseDns: review-b-async.staging.account.gov.uk
    integration:
      BaseDns: review-b-async.integration.account.gov.uk
    production:
      BaseDns: review-b-async.account.gov.uk

  EnvironmentVariables:
    dev:
      STSBASEURL: 'https://sts-mock.review-b-async.dev.account.gov.uk'
      ReadIdBaseUrl: 'https://readid-mock.review-b-async.dev.account.gov.uk/v2'
      ClientRegistrySecretPath: 'dev/clientRegistry'
      BiometricSubmitterKeySecretPathPassport: '/dev/BIOMETRIC_SUBMITTER_ACCESS_KEY_NFC_PASSPORT'
      BiometricSubmitterKeySecretPathBrp: '/dev/BIOMETRIC_SUBMITTER_ACCESS_KEY_NFC_BRP'
      BiometricSubmitterKeySecretPathDl: '/dev/BIOMETRIC_SUBMITTER_ACCESS_KEY_DL'
      BiometricSubmitterKeySecretCacheDurationInSeconds: 900

    build:
      STSBASEURL: 'https://sts-mock.review-b-async.build.account.gov.uk'
      ReadIdBaseUrl: 'https://readid-mock.review-b-async.build.account.gov.uk/v2'
      ClientRegistrySecretPath: 'build/clientRegistry'
      BiometricSubmitterKeySecretPathPassport: '/build/BIOMETRIC_SUBMITTER_ACCESS_KEY_NFC_PASSPORT'
      BiometricSubmitterKeySecretPathBrp: '/build/BIOMETRIC_SUBMITTER_ACCESS_KEY_NFC_BRP'
      BiometricSubmitterKeySecretPathDl: '/build/BIOMETRIC_SUBMITTER_ACCESS_KEY_DL'
      BiometricSubmitterKeySecretCacheDurationInSeconds: 900

    staging:
      STSBASEURL: 'https://token.staging.account.gov.uk'
      ReadIdBaseUrl: '' #TODO: Update this value with new ReadID URL once available
      ClientRegistrySecretPath: 'staging/clientRegistry'
      BiometricSubmitterKeySecretPathPassport: '/staging/BIOMETRIC_SUBMITTER_ACCESS_KEY_NFC_PASSPORT'
      BiometricSubmitterKeySecretPathBrp: '/staging/BIOMETRIC_SUBMITTER_ACCESS_KEY_NFC_BRP'
      BiometricSubmitterKeySecretPathDl: '/staging/BIOMETRIC_SUBMITTER_ACCESS_KEY_DL'
      BiometricSubmitterKeySecretCacheDurationInSeconds: 900

    integration:
      STSBASEURL: 'https://token.integration.account.gov.uk'
      ReadIdBaseUrl: '' #TODO: Update this value with new ReadID URL once available
      ClientRegistrySecretPath: 'integration/clientRegistry'
      BiometricSubmitterKeySecretPathPassport: '/integration/BIOMETRIC_SUBMITTER_ACCESS_KEY_NFC_PASSPORT'
      BiometricSubmitterKeySecretPathBrp: '/integration/BIOMETRIC_SUBMITTER_ACCESS_KEY_NFC_BRP'
      BiometricSubmitterKeySecretPathDl: '/integration/BIOMETRIC_SUBMITTER_ACCESS_KEY_DL'
      BiometricSubmitterKeySecretCacheDurationInSeconds: 900

    production:
      STSBASEURL: 'https://token.account.gov.uk'
      ReadIdBaseUrl: '' #TODO: Update this value with new ReadID URL once available
      ClientRegistrySecretPath: 'production/clientRegistry'
      BiometricSubmitterKeySecretPathPassport: '/production/BIOMETRIC_SUBMITTER_ACCESS_KEY_NFC_PASSPORT'
      BiometricSubmitterKeySecretPathBrp: '/production/BIOMETRIC_SUBMITTER_ACCESS_KEY_NFC_BRP'
      BiometricSubmitterKeySecretPathDl: '/production/BIOMETRIC_SUBMITTER_ACCESS_KEY_DL'
      BiometricSubmitterKeySecretCacheDurationInSeconds: 900

Conditions:
  UseCodeSigning: !Not
    - !Equals
      - !Ref CodeSigningConfigArn
      - none

  UsePermissionsBoundary: !Not
    - !Equals
      - !Ref PermissionsBoundary
      - none

  isDev: !Equals
      - !Ref Environment
      - dev

  isNotDevOrBuild: !Or
    - !Equals
      - !Ref Environment
      - staging
    - !Equals
      - !Ref Environment
      - integration
    - !Equals
      - !Ref Environment
      - production

  IsDevOrBuild: !Or
    - !Equals
      - !Ref Environment
      - dev
    - !Equals
      - !Ref Environment
      - build

  ProxyApiDeployment: !Or
    - !Equals
      - !Ref Environment
      - dev
    - !Equals
      - !Ref Environment
      - build

  UseDevOverrideStsBaseUrl: !Not
    - !Equals
      - !Ref DevOverrideStsBaseUrl
      - none

  DevelopmentStack: !And
    - !Equals [!Ref Environment, dev]
    - !Not [!Equals [!Ref AWS::StackName, mob-async-backend]]

  DeployAlarms: !Or
    - !Not
      - !Equals
        - !Ref Environment
        - dev
    - !Equals [!Ref DeployAlarmsInDev, true]

  IntegrateIpvCore: !Equals
      - !Ref Environment
      - staging

  Never: !Equals
    - !Ref AWS::NoValue
    - "false"

Resources:
  # CloudFormation requires at least one resource definition per template, so this resource is here to satisfy various
  # linting . It has no required properties, will never be deployed, and would have no effect if it were deployed.
  NullResource:
    Type: AWS::CloudFormation::WaitConditionHandle
    Condition: Never

Globals:
  Function:
    AutoPublishAlias: live
    AutoPublishAliasAllProperties: true
    Timeout: 5
    MemorySize: 512
    ReservedConcurrentExecutions: !If
      - isDev
      - !Ref AWS::NoValue
      - !FindInMap
        - Lambda
        - !Ref Environment
        - ReservedConcurrentExecutions
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue
    LoggingConfig:
      ApplicationLogLevel:
        !FindInMap [ Lambda, !Ref Environment, LogLevel ]
      SystemLogLevel: INFO
      LogFormat: JSON
    Architectures:
      - arm64
    Environment:
      Variables:
        SIGNING_KEY_ID: !GetAtt KMSSigningKey.Arn
        TXMA_SQS: !GetAtt TxMASQSQueue.QueueUrl
        # ISSUER should be updated with DNS once available
        ISSUER: mockIssuer
        SESSION_TABLE_NAME: !Ref SessionsTable
        POWERTOOLS_SERVICE_NAME: mobile-id-check-async-backend
        AWS_LAMBDA_EXEC_WRAPPER: /opt/dynatrace
        DT_CONNECTION_AUTH_TOKEN: !Sub
          - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CONNECTION_AUTH_TOKEN}}'
          - SecretArn: !FindInMap [EnvironmentConfiguration, !Ref Environment, dynatraceSecretArn]
        DT_CONNECTION_BASE_URL: !Sub
          - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CONNECTION_BASE_URL}}'
          - SecretArn: !FindInMap [EnvironmentConfiguration, !Ref Environment, dynatraceSecretArn]
        DT_CLUSTER_ID: !Sub
          - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_CLUSTER_ID}}'
          - SecretArn: !FindInMap [EnvironmentConfiguration, !Ref Environment, dynatraceSecretArn]
        DT_LOG_COLLECTION_AUTH_TOKEN: !Sub
          - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_LOG_COLLECTION_AUTH_TOKEN}}'
          - SecretArn: !FindInMap [EnvironmentConfiguration, !Ref Environment, dynatraceSecretArn]
        DT_TENANT: !Sub
          - '{{resolve:secretsmanager:${SecretArn}:SecretString:DT_TENANT}}'
          - SecretArn: !FindInMap [EnvironmentConfiguration, !Ref Environment, dynatraceSecretArn]
        DT_OPEN_TELEMETRY_ENABLE_INTEGRATION: "true"
    Layers:
      - !Sub
        - '{{resolve:secretsmanager:${SecretArn}:SecretString:NODEJS_LAYER}}'
        - SecretArn: !FindInMap [EnvironmentConfiguration, !Ref Environment, dynatraceSecretArn]

Outputs:
  SessionsApiUrl:
    Description: Sessions API Gateway base URL
    Value: !Sub https://${SessionsApiDomainName}

  ProxyApiUrl:
    Condition: ProxyApiDeployment
    Description: Proxy API Gateway Pretty DNS
    Value: !Sub https://${ProxyApiDomainName}

  PrivateApiUrl:
    Description: Private API Gateway base URL
    Value: !Sub https://${PrivateApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}

  StsMockApiUrl:
    Description: STS Mock API Gateway base URL
    Value: !If
      - UseDevOverrideStsBaseUrl
      - !Ref DevOverrideStsBaseUrl
      - !FindInMap [EnvironmentVariables, !Ref Environment, STSBASEURL]

  TxmaSqsQueueArn:
    Condition: IsDevOrBuild
    Description: TxMA SQS Queue ARN
    Export:
      Name: !Sub ${AWS::StackName}-txma-sqs-queue-arn
    Value: !GetAtt TxMASQSQueue.Arn

  TxmaKmsEncryptionKeyArn:
    Condition: IsDevOrBuild
    Description: TxMA KMS Encryption Key ARN
    Export:
      Name: !Sub ${AWS::StackName}-txma-kms-encryption-key-arn
    Value: !GetAtt TxMAKMSEncryptionKey.Arn