AWSTemplateFormatVersion: "2010-09-09"
Resources:
  IPVCoreSqsAgeOfOldestMessageAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: DeployAlarms
    Properties:
      ActionsEnabled: true
      AlarmDescription: !Sub
        - "Trigger an alarm when the age of the oldest message in IPV Core SQS queue is 5 minutes or older. See runbook: ${RunbookUrl}"
        - RunbookUrl: !FindInMap [StaticVariables, WarningAlarmsRunbook, value]
      AlarmName: !Sub "${AWS::StackName}-ipv-core-sqs-age-of-oldest-message"
      AlarmActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-warning"
      OKActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-warning"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
      Threshold: 300
      MetricName: ApproximateAgeOfOldestMessage
      Namespace: AWS/SQS
      Period: 60
      Statistic: Maximum
      Dimensions:
        - Name: QueueName
          Value: !GetAtt IPVCoreOutboundSqs.QueueName

  IPVCoreDlqMessageVisibleLowThresholdAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: DeployAlarms
    Properties:
      ActionsEnabled: true
      AlarmDescription: !Sub
        - "Trigger a warning alarm when message gets added to IPV Core SQS DLQ. See runbook: ${RunbookUrl}"
        - RunbookUrl: !FindInMap [StaticVariables, WarningAlarmsRunbook, value]
      AlarmName: !Sub "${AWS::StackName}-low-threshold-ipv-core-dlq-message-visible"
      AlarmActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-warning"
      OKActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-warning"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
      Threshold: 1
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Period: 60
      Statistic: Maximum
      Dimensions:
        - Name: QueueName
          Value: !GetAtt IPVCoreOutboundDlq.QueueName

  IPVCoreDlqMessageInflowVsStartedAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: DeployAlarms
    DependsOn:
      - "AsyncIssueBiometricCredentialCompletionMetricFilter"
    Properties:
      ActionsEnabled: true
      AlarmDescription: !Sub
        - "Critical when DLQ inflow is >= 25% of MOBILE_ASYNC_ISSUE_BIOMETRIC_CREDENTIAL_STARTED for 2 of the last 5 minutes. Will only evaluate when there is at least 40 MOBILE_ASYNC_ISSUE_BIOMETRIC_CREDENTIAL_STARTED logs per minute. See support manual: ${SupportManualUrl}"
        - SupportManualUrl: !FindInMap [StaticVariables, SupportManual, value]
      AlarmName: !Sub "${AWS::StackName}-ipv-core-dlq-message-inflow-vs-started"
      AlarmActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-warning"
      OKActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-warning"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 25
      EvaluationPeriods: 5
      DatapointsToAlarm: 2
      TreatMissingData: notBreaching
      Metrics:
        - Id: lambdaLogStarted
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: !Sub "${AWS::StackName}/LogMessages"
              MetricName: AsyncIssueBiometricCredentialMessageCode
              Dimensions:
                - Name: MessageCode
                  Value: MOBILE_ASYNC_ISSUE_BIOMETRIC_CREDENTIAL_STARTED
                - Name: Version
                  Value: !GetAtt AsyncIssueBiometricCredentialFunction.Version.Version
            Period: 60
            Stat: Sum
        - Id: dlqMessageInflow
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: AWS/SQS
              MetricName: NumberOfMessagesSent
              Dimensions:
                - Name: QueueName
                  Value: !GetAtt IPVCoreOutboundDlq.QueueName
            Period: 60
            Stat: Sum
        - Id: dlqMessageInflowPercentage
          Label: "DLQ inflow as % of STARTED log"
          ReturnData: true
          Expression: "IF(FILL(lambdaLogStarted,0) >= 40, 100 * dlqMessageInflow / FILL(lambdaLogStarted,0), 0)"

  IPVCoreDlqAgeOfOldestMessageLowThresholdAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: DeployAlarms
    Properties:
      ActionsEnabled: true
      AlarmDescription: !Sub
        - "Trigger an alarm when the age of the oldest message in IPV Core SQS DLQ is 3 days or older. See runbook: ${RunbookUrl}"
        - RunbookUrl: !FindInMap [StaticVariables, WarningAlarmsRunbook, value]
      AlarmName: !Sub "${AWS::StackName}-low-threshold-ipv-core-dlq-age-of-oldest-message"
      AlarmActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-warning"
      OKActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-warning"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
      Threshold: 259200
      MetricName: ApproximateAgeOfOldestMessage
      Namespace: AWS/SQS
      Period: 60
      Statistic: Maximum
      Dimensions:
        - Name: QueueName
          Value: !GetAtt IPVCoreOutboundDlq.QueueName