AWSTemplateFormatVersion: "2010-09-09"
Resources:
  PrivateApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-private-api
      Description: Private API gateway for Client Credentials flow
      AlwaysDeploy: true
      EndpointConfiguration:
        Type: PRIVATE
        VPCEndpointIds: 
          - !If
            - IntegrateIpvCore
            - !FindInMap
              - EnvironmentVariables
              - IpvCoreVpceId
              - !Ref Environment
            - Ref: "AWS::NoValue"
          - !If
            - IntegratePerformanceTesting
            - !FindInMap
              - EnvironmentVariables
              - PerformanceTestingVpceId
              - !Ref Environment
            - Ref: "AWS::NoValue"
      Auth:
        ResourcePolicy:
          IntrinsicVpceWhitelist:
            - !ImportValue devplatform-vpc-ExecuteApiGatewayEndpointId
            - !If
              - IntegrateIpvCore
              - !FindInMap
                - EnvironmentVariables
                - IpvCoreVpceId
                - !Ref Environment
              - Ref: "AWS::NoValue"
            - !If
              - IntegratePerformanceTesting
              - !FindInMap
                - EnvironmentVariables
                - PerformanceTestingVpceId
                - !Ref Environment
              - Ref: "AWS::NoValue"
      StageName: !Ref Environment
      OpenApiVersion: 3.0.1
      AccessLogSetting:
        DestinationArn: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${AsyncPrivateApiAccessLogs}
        Format: '{ "requestId":"$context.requestId", "ip": "$context.identity.sourceIp", "caller":"$context.identity.caller", "user":"$context.identity.user","requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod","resourcePath":"$context.resourcePath", "status":"$context.status","protocol":"$context.protocol", "responseLength":"$context.responseLength" }'
      MethodSettings:
        - LoggingLevel: INFO
          ResourcePath: /*
          HttpMethod: '*'
          DataTraceEnabled: false
          MetricsEnabled: true
          ThrottlingBurstLimit: !FindInMap
            - EnvironmentVariables
            - PrivateApiBurstLimit
            - !Ref Environment
          ThrottlingRateLimit: !FindInMap
            - EnvironmentVariables
            - PrivateApiRateLimit
            - !Ref Environment
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./openApiSpecs/async-private-spec.yaml

  AsyncPrivateApiAccessLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/${AWS::StackName}-private-api-access-logs
      RetentionInDays: 30

  AsyncPrivateApiSubscriptionFilter:    
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      DestinationArn: 
        !FindInMap [EnvironmentVariables, CslsEgress, !Ref Environment]
      FilterPattern: ""
      LogGroupName: !Ref AsyncPrivateApiAccessLogs
    Condition: isNotDev