version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    ignore:
      - dependency-name: "govuk-one-login/devplatform-upload-action"
        versions: [ "b7994fb959f70cc1440295de9e823f317ffa197e" ]
    open-pull-requests-limit: 5
    groups:
      gha-version:
        applies-to: version-updates
        patterns:
          - "*"
      gha-security:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "backend-api"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "03:00"
    open-pull-requests-limit: 5
    groups:
      backend-version:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      backend-security:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"