# version: 2
# updates:
#   - package-ecosystem: "github-actions"
#     directory: "/"
#     schedule:
#       interval: "daily"
#       time: "03:00"
#     open-pull-requests-limit: 2
#     groups:
#       gha-version:
#         applies-to: version-updates
#         patterns:
#           - "*"
#       gha-security:
#         applies-to: security-updates
#         patterns:
#           - "*"

# npm --------------------------------------------------------------------------
  # - package-ecosystem: "npm"
  #   directory: "/async-credential"
  #   schedule:
  #     interval: "daily"
  #     time: "03:00"
  #   open-pull-requests-limit: 2
  #   groups:
  #     async-credential-version:
  #       applies-to: version-updates
  #       patterns:
  #         - "*"
  #       update-types:
  #         - "minor"
  #         - "patch"
  #     async-credential-security:
  #       applies-to: security-updates
  #       patterns:
  #         - "*"
  #       update-types:
  #         - "minor"
  #         - "patch"
