repos:
  - repo: local
    hooks:
      - id: merge-templates
        name: Merge CloudFormation Templates
        entry: scripts/merge-templates.sh
        language: script
        files: ^cloudFormation/.*\.yaml$