AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Description: The environment type
  StackName:
    Type: String
    Description: Name of the parent stack
  TxmaAccount:
    Type: String
    Description: TxMA Account ID
  TxMAKmsKeyId:
    Type: String
    Description: KMS Key ID for TxMA

Conditions:
  isNotDevOrBuild: !Or 
    - !Equals [!Ref Environment, staging]
    - !Equals [!Ref Environment, integration]
    - !Equals [!Ref Environment, production]

Resources:
  TxMASQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 604800
      VisibilityTimeout: 60
      KmsMasterKeyId: !Ref TxMAKmsKeyId
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TxMASQSQueueDeadLetterQueue.Arn
        maxReceiveCount: 5

  TxMASQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Condition: isNotDevOrBuild
    Properties:
      Queues:
        - !Ref TxMASQSQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:ChangeMessageVisibility
              - sqs:ReceiveMessage
            Resource:
              - !GetAtt TxMASQSQueue.Arn
            Principal:
              AWS: !Ref TxmaAccount

  TxMASQSQueueDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 259200
      KmsMasterKeyId: !Ref TxMAKmsKeyId

Outputs:
  QueueUrl:
    Description: TxMA SQS Queue URL
    Value: !Ref TxMASQSQueue
  
  QueueArn:
    Description: TxMA SQS Queue ARN
    Value: !GetAtt TxMASQSQueue.Arn

  DeadLetterQueueUrl:
    Description: TxMA SQS Dead Letter Queue URL
    Value: !Ref TxMASQSQueueDeadLetterQueue
  
  DeadLetterQueueArn:
    Description: TxMA SQS Dead Letter Queue ARN
    Value: !GetAtt TxMASQSQueueDeadLetterQueue.Arn