AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM template for the test resources stack. This contains the asynchronous events test harness and the sts-mock applications.

Globals:
  Function:
    AutoPublishAlias: live
    AutoPublishAliasAllProperties: true
    CodeSigningConfigArn: !If
      - UseCodeSigning
      - !Ref CodeSigningConfigArn
      - !Ref AWS::NoValue
    PermissionsBoundary: !If
      - UsePermissionsBoundary
      - !Ref PermissionsBoundary
      - !Ref AWS::NoValue

Parameters:
  Environment:
    Description: The name of the deployment environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - build

  CodeSigningConfigArn:
    Type: String
    Description: >
      The ARN of the Code Signing Config to use, provided by the deployment pipeline
    Default: "none"

  PermissionsBoundary:
      Description: |
        The ARN of the permissions boundary to apply to any role created by the template
      Type: String
      Default: none

  BackendStackName:
    Description: |
      The Stack name of the Async Backend API stack
    Type: String
    Default: mob-async-backend

  DevOverrideProxyBaseUrl:
    Description: |
      Override the Proxy URL used in the API tests
    Type: String
    Default: none

  DevOverrideSessionsBaseUrl:
    Description: |
      Override the Sessions URL used in the API tests
    Type: String
    Default: none

  SamValidateLintWorkaround:
    Description: Do not update or override. This allows the definition of a resource that is never deployed.
    Type: String
    Default: unused

Mappings:
  StsMockApiGateway:
    dev:
      ApiBurstLimit: 10
      ApiRateLimit: 10
    build:
      ApiBurstLimit: 10
      ApiRateLimit: 10

  EventsApiGateway:
    dev:
      ApiBurstLimit: 10
      ApiRateLimit: 10
    build:
      ApiBurstLimit: 10
      ApiRateLimit: 10

  TestResourcesApiGateway:
    dev:
      ApiBurstLimit: 10
      ApiRateLimit: 10
    build:
      ApiBurstLimit: 10
      ApiRateLimit: 10

  DNS:
    dev:
      BaseDns: review-b-async.dev.account.gov.uk
    build:
      BaseDns: review-b-async.build.account.gov.uk

Conditions:
  NeverDeploy: !Equals
    - !Ref SamValidateLintWorkaround
    - "Should always equal false"

  UseCodeSigning:
    Fn::Not:
      - Fn::Equals:
          - !Ref CodeSigningConfigArn
          - "none"

  UsePermissionsBoundary: !Not
    - !Equals
      - !Ref PermissionsBoundary
      - none

  UseDevOverrideProxyBaseUrl: !Not
    - !Equals
      - !Ref DevOverrideProxyBaseUrl
      - none

  UseDevOverrideSessionsBaseUrl: !Not
    - !Equals
      - !Ref DevOverrideSessionsBaseUrl
      - none

  DevelopmentStack: !And
    - !Equals
      - !Ref Environment
      - dev
    - !Not
      - !Equals
        - !Ref AWS::StackName
        - mob-test-resources

Resources:
  # CloudFormation requires at least one resource definition per template, so this resource is here to satisfy various
  # linting . It has no required properties, will never be deployed, and would have no effect if it were deployed.
  NullResource:
    Type: AWS::CloudFormation::WaitConditionHandle
    Condition: NeverDeploy

Outputs:
  StsMockApiUrl:
    Description: STS Mock API Gateway DNS
    Value: !Sub https://${StsMockApiDomainName}

  EventsApiUrl:
    Description: Events API URL
    Value: !Sub https://${EventsApiDomainName}

  ProxyApiUrl:
    Description: Proxy API URL used in the Events API tests
    Value: !If
      - UseDevOverrideProxyBaseUrl
      - !Ref DevOverrideProxyBaseUrl
      - !Sub https://proxy.review-b-async.${Environment}.account.gov.uk

  SessionsApiUrl:
    Description: Sessions API URL used in the Events API tests
    Value: !If
      - UseDevOverrideSessionsBaseUrl
      - !Ref DevOverrideSessionsBaseUrl
      - !Sub https://sessions.review-b-async.${Environment}.account.gov.uk
  TestResourcesApiUrl:
    Description: Test Resources API Gateway Url
    Value: !Sub https://${TestResourcesApiDomainName}
