import { RegisteredLogMessages } from "../services/logging/types";

export type MessageName =
  | "STARTED"
  | "COMPLETED"
  | "ENVIRONMENT_VARIABLE_MISSING"
  | "FAILED_TO_PROCESS_MESSAGES"
  | "PROCESSED_MESSAGES"
  | "ERROR_WRITING_EVENT_TO_DEQUEUE_TABLE";

export const registeredLogs: RegisteredLogMessages<MessageName> = {
  STARTED: {
    messageCode: "TEST_RESOURCES_STARTED",
  },
  COMPLETED: {
    messageCode: "TEST_RESOURCES_COMPLETED",
  },
  ENVIRONMENT_VARIABLE_MISSING: {
    messageCode: "TEST_RESOURCES_ENVIRONMENT_VARIABLE_MISSING",
  },
  FAILED_TO_PROCESS_MESSAGES: {
    messageCode: "TEST_RESOURCES_FAILED_TO_PROCESS_MESSAGES",
  },
  PROCESSED_MESSAGES: {
    messageCode: "TEST_RESOURCES_PROCESSED_MESSAGES",
  },
  ERROR_WRITING_EVENT_TO_DEQUEUE_TABLE: {
    messageCode: "TEST_RESOURCES_ERROR_WRITING_EVENT_TO_DEQUEUE_TABLE",
  },
};
