AWSTemplateFormatVersion: "2010-09-09"
Resources:
  AsyncIssueBiometricCredentialCompletionMetricFilter:
    Condition: DeployAlarms
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref AsyncIssueBiometricCredentialLogGroup
      FilterPattern: "{ ($.messageCode = *) && ($.functionVersion = *) }"
      MetricTransformations:
        - MetricValue: "1"
          MetricNamespace: !Sub "${AWS::StackName}/LogMessages"
          MetricName: "AsyncIssueBiometricCredentialMessageCode"
          Dimensions:
            - Key: MessageCode
              Value: $.messageCode
            - Key: Version
              Value: $.functionVersion

  AsyncIssueBiometricCredentialTimeToIssueVcMetricFilter:
    Condition: DeployAlarms
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref AsyncIssueBiometricCredentialLogGroup
      FilterPattern: '{ ($.messageCode = "MOBILE_ASYNC_ISSUE_BIOMETRIC_CREDENTIAL_VC_ISSUED") && ($.documentType = *) && ($.vendorProcessingQueueToVcIssuanceElapsedTimeInMs = *) }'
      MetricTransformations:
        - Dimensions:
            - Key: DocumentType
              Value: $.documentType
          MetricName: AsyncIssueBiometricCredentialTimeToIssueVc
          MetricNamespace: !Sub ${AWS::StackName}/LogMessages
          MetricValue: $.vendorProcessingQueueToVcIssuanceElapsedTimeInMs
          Unit: Milliseconds

  AsyncIssueBiometricCredentialReceiveCountMetricFilter:
    Condition: DeployAlarms
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: '{ ($.sqsMessageProperties.approximateReceiveCount = *) && ($.documentType = *) && ($.messageCode = *) }'
      LogGroupName: !Ref AsyncIssueBiometricCredentialLogGroup
      MetricTransformations:
        - Dimensions:
            - Key: ReceiveCount
              Value: $.sqsMessageProperties.approximateReceiveCount
            - Key: DocumentType
              Value: $.documentType
            - Key: MessageCode
              Value: $.messageCode
          MetricName: AsyncIssueBiometricCredentialReceiveCount
          MetricNamespace: !Sub ${AWS::StackName}/LogMessages
          MetricValue: "$.sqsMessageProperties.approximateReceiveCount"