AWSTemplateFormatVersion: "2010-09-09"
Resources:
  AsyncTokenCompletionMetricFilter:
    Condition: DeployAlarms
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref AsyncTokenLogGroup
      FilterPattern: "{ ($.messageCode = *) && ($.functionVersion = *) }"
      MetricTransformations:
        - MetricValue: "1"
          MetricNamespace: !Sub "${AWS::StackName}/LogMessages"
          MetricName: "AsyncTokenMessageCode"
          Dimensions:
            - Key: MessageCode
              Value: $.messageCode
            - Key: Version
              Value: $.functionVersion