#!/bin/sh

# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

set -e

cd backend-api || exit 1

# Run prettier formatting checks
npm run lint
npm run format:check