AWSTemplateFormatVersion: "2010-09-09"
Resources:
  CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - codedeploy.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRoleForLambda
      PermissionsBoundary:
        !If [
          UsePermissionsBoundary,
          !Ref PermissionsBoundary,
          !Ref AWS::NoValue,
        ]
      RoleName: !Sub ${AWS::StackName}-code-deploy-service-role

  # DeploymentConfig is used to describe the traffic shifting pattern for blue/green deploys used for lambdas.
  Linear20PercentEvery1Minute:
    Type: AWS::CodeDeploy::DeploymentConfig
    Properties:
      DeploymentConfigName: !Sub ${AWS::StackName}-Linear20PercentEvery1Minute
      ComputePlatform: Lambda
      TrafficRoutingConfig:
        Type: TimeBasedLinear
        TimeBasedLinear:
          LinearInterval: 1
          LinearPercentage: 20
