FROM node:iron-alpine AS builder

WORKDIR /backend-api

# Create a new user 'test' to avoid running the app as a root
RUN adduser --disabled-password test
RUN chown test .

COPY package.json package-lock.json ./
RUN npm install


## Update container and install awscli
RUN apk upgrade && apk update; apk add --no-cache aws-cli bash
RUN aws --version

# Copy the CloudFormation infrastructure template and application source code to the working directory
COPY template.yaml /
COPY src ./

# Give user, 'test', permissions to execute test script and switch the user to 'test'
COPY run-tests.sh /
RUN chmod 005 /run-tests.sh
USER test

ENTRYPOINT ["/run-tests.sh"]
