export const protectedStacks = [
  "mob-test-resources",
  "mob-test-resources-tir",
  "mob-test-resources-pl",
  "mob-async-backend",
  "mob-async-backend-tir",
  "mob-async-backend-pl",
  "mob-async-backend-cf-dist",
  "mob-readid-mock",
  "mob-readid-mock-tir",
  "mob-readid-mock-pl",
  "mob-async-readid-proxy",
  "mob-async-readid-proxy-tir",
  "mob-async-readid-proxy-pl",
];
