AWSTemplateFormatVersion: "2010-09-09"

Resources:
  AsyncIssueBiometricCredentialFunction:
    Type: AWS::Serverless::Function
    DependsOn:
      - AsyncIssueBiometricCredentialLogGroup
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: false
        EntryPoints:
          - src/functions/asyncIssueBiometricCredential/asyncIssueBiometricCredentialHandler.ts
    Properties:
      FunctionName: !Sub ${AWS::StackName}-issue-biometric-credential
      Runtime: nodejs20.x
      Handler: asyncIssueBiometricCredentialHandler.lambdaHandler
      Events:
        AsyncIssueBiometricCredential:
          Type: Api
          Properties:
            Path: /async/issueBiometricCredential
            Method: post
            RestApiId: !Ref SessionsApi
      Role: !GetAtt AsyncIssueBiometricCredentialLambdaRole.Arn
      VpcConfig:
        SubnetIds:
          - !ImportValue devplatform-vpc-ProtectedSubnetIdA
          - !ImportValue devplatform-vpc-ProtectedSubnetIdB
          - !ImportValue devplatform-vpc-ProtectedSubnetIdC
        SecurityGroupIds:
          - !ImportValue devplatform-vpc-AWSServicesEndpointSecurityGroupId