AWSTemplateFormatVersion: "2010-09-09"
Resources:
  AsyncBackoffRetryDemoMetricFilter:
    Type: AWS::Logs::MetricFilter
    Condition: DeployAlarms
    Properties:
      LogGroupName: !Ref AsyncBackoffRetryDemoLogGroup
      FilterPattern: '{ $.messageCode = * }'
      MetricTransformations:
        - MetricValue: "1"
          MetricNamespace: !Sub "${AWS::StackName}/LogMessages"
          MetricName: "AsyncBackoffRetryDemoMessageCode"
          Dimensions:
            - Key: MessageCode
              Value: $.messageCode

  AsyncBackoffRetryDemoCompletionMetricFilter:
    Condition: DeployAlarms
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref AsyncBackoffRetryDemoLogGroup
      FilterPattern: "{ ($.messageCode = *) && ($.functionVersion = *) }"
      MetricTransformations:
        - MetricValue: "1"
          MetricNamespace: !Sub "${AWS::StackName}/LogMessages"
          MetricName: "AsyncBackoffRetryDemoMessageCode"
          Dimensions:
            - Key: MessageCode
              Value: $.messageCode
            - Key: Version
              Value: $.functionVersion
