AWSTemplateFormatVersion: "2010-09-09"

Description: |
  A set of KMS resources to handle Encryption and Signing at account level

Parameters:
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production
    Default: dev

Resources:
  KMSSigningKey:
    Type: AWS::KMS::Key
    Properties:
      Description: A KMS Key for signing.
      Enabled: true
      EnableKeyRotation: false
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - kms:*
            Resource:
              - '*'
      KeySpec: ECC_NIST_P256
      KeyUsage: SIGN_VERIFY
      MultiRegion: false
      PendingWindowInDays: 7
      Tags:
        - Key: KeyType
          Value: Test Signing Key
        - Key: Environment
          Value: !Sub ${Environment}

  KMSSigningKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/signing-key
      TargetKeyId: !Ref KMSSigningKey

  KMSEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: A KMS Key for encrypting.
      Enabled: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - kms:*
            Resource:
              - '*'
      KeySpec: RSA_2048
      KeyUsage: ENCRYPT_DECRYPT
      MultiRegion: false
      PendingWindowInDays: 7
      Tags:
        - Key: KeyType
          Value: Encryption Key
        - Key: Environment
          Value: !Sub ${Environment}

  KMSEncryptionKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/encryption-key
      TargetKeyId: !Ref KMSEncryptionKey

Outputs:
  SigningKeyArn:
    Description: The Arn of the signing key
    Value: !GetAtt KMSSigningKey.Arn
    Export:
      Name: !Sub ${AWS::StackName}-signing-key-arn

  SigningKeyAlias:
    Description: The Alias of the signing key
    Value: !Ref KMSSigningKeyAlias

  EncryptionKeyArn:
    Description: The ARN of the encryption key
    Value: !GetAtt KMSEncryptionKey.Arn
    Export:
      Name: !Sub ${AWS::StackName}-encryption-key-arn

  EncryptionKeyAlias:
    Description: The ARN of the test encryption key
    Value: !Ref KMSEncryptionKeyAlias
