AWSTemplateFormatVersion: "2010-09-09"
Resources:
  IPVCoreOutboundSQS:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 345600 # 4 days in seconds
      VisibilityTimeout: 60
      DelaySeconds: 0
      KmsMasterKeyId: !Ref IPVCoreOutboundKeyAlias
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt IPVCoreOutboundSQSDeadLetterQueue.Arn
        maxReceiveCount: 60

  IPVCoreOutboundSQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref IPVCoreOutboundSQS
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:ChangeMessageVisibility
              - sqs:ReceiveMessage
            Resource:
              - !GetAtt IPVCoreOutboundSQS.Arn
            Principal:
              AWS:
                - !FindInMap
                  - IPVCore
                  - !Ref Environment
                  - AccountId
    Condition: isNotDevOrBuild

  IPVCoreOutboundSQSDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 345600 # 4 days in seconds
      KmsMasterKeyId: !Ref IPVCoreOutboundKMSEncryptionKey

  IPVCoreOutboundKMSEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: A KMS Key for encrypting the SQS for IPVCore outbound messages
      Enabled: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - kms:*
            Resource:
              - "*"
          - Effect: Allow
            Principal:
              AWS: !FindInMap
                - IPVCore
                - !Ref Environment
                - AccountId
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource:
              - "*"
      KeySpec: SYMMETRIC_DEFAULT
      KeyUsage: ENCRYPT_DECRYPT
      MultiRegion: false
      PendingWindowInDays: !FindInMap
        - KMS
        - !Ref Environment
        - PendingDeletionInDays

  IPVCoreOutboundKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${AWS::StackName}-IPVCoreOutboundKMSEncryptionKey
      TargetKeyId: !Ref IPVCoreOutboundKMSEncryptionKey