openapi: 3.0.0
info:
  title: GOV.UK One Login mobile app - API for asynchronous issuing of credentials
  version: 1.0.0
  description: GOV.UK One Login mobile app - API for asynchronous issuing of credentials

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      in: header
    bearerAuth:
      type: http
      scheme: bearer
      in: header
  schemas:
    ServerError:
      type: object
      properties:
        error:
          type: string
          enum:
            - server_error
          description: |
            The error code.
        error_description:
          type: string
          description: |
            A description of the error.
      required:
        - error
        - error_description
    CredentialResponse:
      type: object
      properties:
        sub:
          type: string
          description: |
            The access token value is a DCMAW-signed JWT which you can use with DCMAW APIs.
        "https://vocab.account.gov.uk/v1/credentialStatus":
          type: string
          enum:
            - pending
          description: |
            The status of the request at the time of creation.
      required:
        - sub
        - "https://vocab.account.gov.uk/v1/credentialStatus"

paths:
  /async/token:
    post:
      summary: Exchange Client Credentials for a scoped access token.
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  enum:
                    - client_credentials
                  example: client_credentials
                  description: |
                    For client credentials grant flow this value must be specified as above.
              required:
                - grant_type
      responses:
        '200':
          description: OK
          content:
            application/json:
              examples:
                success:
                  value: 
                    {
                      "access_token": "eJY_EXAMPLE",
                      "token_type": "bearer",
                      "expires_in": 180
                    }
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: |
                      The access token value is an access token represented as a DCMAW-signed JWT which you can use with DCMAW APIs.
                  token_type:
                    type: string
                    enum:
                      - bearer
                    description: |
                      The token type value. DCMAW only supports the [bearer token](https://oauth.net/2/bearer-tokens/).
                  expires_in:
                    type: integer
                    description: |
                      The length of time the token is valid for in seconds.
                required:
                  - access_token
                  - token_type
                  - expires_in
        '400':
          description: Bad request
          content:
            application/json:
              examples:
                errorInvalidGrant:
                  description: |
                    The grant type is missing or the value provided is not supported by the server.
                    OR
                    Client authentication failed because the provided client details do not match a registered client. To resolve, check your client ID matches the client ID you had when you [registered your service to use GOV.UK One Login](https://docs.sign-in.service.gov.uk/integrate-with-integration-environment/manage-your-service-s-configuration/#register-your-service-to-use-gov-uk-one-login).
                  value:
                    {
                      "error": "invalid_grant",
                      "error_description": "Invalid grant"
                    }
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum:
                      - invalid_grant
                    description: |
                      The error code.
                  error_description:
                    type: string
                    description: |
                      A description of the error.
                required:
                  - error
                  - error_description
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                errorInvalidClient:
                  description: |
                    The authorization header is missing or is invalid.
                  value:
                    {
                      "error": "invalid_client",
                      "error_description": "Invalid or missing authorization header"
                    }
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum:
                      - invalid_client
                    description: |
                      The error code.
                  error_description:
                    type: string
                    description: |
                      A description of the error.
                required:
                  - error
                  - error_description
        '500':
          description: Internal server error
          content:
            application/json:
              examples:
                error:
                  description: |
                    The service encountered an unrecoverable error when trying to access its internal resources.
                  value:
                    {
                      "error": "server_error",
                      "error_description": "Server Error"
                    }
              schema:
                $ref: "#/components/schemas/ServerError"
      x-amazon-apigateway-integration:
        requestTemplates:
          application/json:
            statusCode: 200
        httpMethod: "POST"
        passthroughBehavior: "when_no_match"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AsyncTokenFunction}/invocations"
        type: "aws_proxy"
  /async/credential:
    post:
      summary: Submit a JAR to start a new DCMAW session.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sub:
                  type: string
                  example: urn:fdc:gov.uk:2022:56P4CMsGh_02YOlWpd8PAOI-2sVlB2nsNU7mcLZYhYw=
                govuk_signin_journey_id:
                  type: string
                  example: 44444444-4444-4444-4444-444444444444
                client_id:
                  type: string
                  example: CLIENT_ID
                state:
                  type: string
                  example: RANDOM_VALUE
                redirect_uri:
                  type: string
                  example: https://example/redirect
              required:
                - sub
                - govuk_signin_journey_id
                - client_id
                - state
                - redirect_uri
      responses:
        '201':
          description: Created
          content:
            application/json:
              examples:
                success:
                  value:
                    {
                      "sub": "urn:fdc:gov.uk:2022:56P4CMsGh_02YOlWpd8PAOI-2sVlB2nsNU7mcLZYhYw=",
                      "https://vocab.account.gov.uk/v1/credentialStatus": "pending"
                    }
              schema:
                $ref: "#/components/schemas/CredentialResponse"
        '200':
          description: OK
          content:
            application/json:
              examples:
                success:
                  value:
                    {
                      "sub": "urn:fdc:gov.uk:2022:56P4CMsGh_02YOlWpd8PAOI-2sVlB2nsNU7mcLZYhYw=",
                      "https://vocab.account.gov.uk/v1/credentialStatus": "pending"
                    }
              schema:
                $ref: "#/components/schemas/CredentialResponse"
        '400':
          description: Bad request
          content:
            application/json:
              examples:
                errorInvalidRequest:
                  description: |
                    The request body is missing or is invalid.
                  value:
                    {
                      "error": "invalid_request",
                      "error_description": "Request body validation failed"
                    }
                errorInvalidToken:
                  description: |
                    The access token could not be decoded, its payload is invalid or its signature could not be verified.
                  value:
                    {
                      "error": "invalid_token",
                      "error_description": "Invalid signature"
                    }
                errorInvalidClient:
                  description: |
                    The provided client details do not match a registered client.
                  value:
                    {
                      "error": "invalid_client",
                      "error_description": "Supplied client not recognised"
                    }
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum:
                      - invalid_request
                      - invalid_token
                      - invalid_client
                    description: |
                      The error code.
                  error_description:
                    type: string
                    description: |
                      A description of the error.
                required:
                  - error
                  - error_description
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                errorInvalidAccessToken:
                  description: |
                    The authorization header is missing or is invalid.
                  value:
                    {
                      "error": "invalid_token",
                      "error_description": "Invalid or missing authorization header"
                    }
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum:
                      - invalid_token
                    description: |
                      The error code.
                  error_description:
                    type: string
                    description: |
                      A description of the error.
                required:
                  - error
                  - error_description
        '500':
          description: Internal server error
          content:
            application/json:
              examples:
                error:
                  description: |
                    The server has encountered an unexpected condition or configuration problem that prevents 
                    it from fulfilling the request made by the browser or client.
                  value:
                    {
                      "error": "server_error",
                      "error_description": "Server error"
                    }
              schema:
                $ref: "#/components/schemas/ServerError"
      x-amazon-apigateway-integration:
        requestTemplates:
          application/json:
            statusCode: 200
        httpMethod: "POST"
        passthroughBehavior: "when_no_match"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AsyncCredentialFunction}/invocations"
        type: "aws_proxy"