openapi: 3.0.0
info:
  title: GOV.UK One Login mobile app - API for asynchronous issuing of credentials
  version: 1.0.0
  description: GOV.UK One Login mobile app - API for asynchronous issuing of credentials

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    InternalServerError:
      type: object
      properties:
        error:
          type: string
          enum:
            - server_error
          description: |
            The error code.
        error_description:
          type: string
          description: |
            A description of the error.
      required:
        - error
        - error_description

paths:
  /async/token:
    post:
      summary: Exchange Client Credentials for a scoped access token
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  enum:
                    - client_credentials
                  example: client_credentials
                  description: |
                    For client credentials grant flow this value must be specified as above
              required:
                - grant_type
      responses:
        '200':
          description: OK
          content:
            application/json:
              examples:
                success:
                  value: 
                    {
                      "access_token": "eJY_EXAMPLE",
                      "token_type": "bearer",
                      "expires_in": 180
                    }
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: |
                      The access token value is an access token represented as a DCMAW-signed JWT which you can use with DCMAW APIs
                  token_type:
                    type: string
                    enum:
                      - bearer
                    description: |
                      The token type value. DCMAW only supports the [bearer token](https://oauth.net/2/bearer-tokens/).
                  expires_in:
                    type: integer
                    description: |
                      The length of time the token is valid for. This is displayed in seconds.
                required:
                  - access_token
                  - token_type
                  - expires_in
        '400':
          description: Bad request
          content:
            application/json:
              examples:
                errorInvalidClient:
                  description: |
                    Client authentication failed, which could be caused by the request containing an invalid client ID.
                    To resolve, check your client ID matches the client ID you had when you [registered your service to use GOV.UK One Login](https://docs.sign-in.service.gov.uk/integrate-with-integration-environment/manage-your-service-s-configuration/#register-your-service-to-use-gov-uk-one-login).
                  value:
                    {
                      "error": "invalid_client",
                      "error_description": "Invalid client"
                    }
                errorInvalidGrant:
                  description: |
                    The grant type is missing or the value provided is not supported by the server.
                  value:
                    {
                      "error": "invalid_grant",
                      "error_description": "Invalid grant"
                    }
              schema:
                type: object
                properties:
                  error:
                    type: string
                    enum:
                      - invalid_grant
                      - invalid_client
                    description: |
                      The error code.
                  error_description:
                    type: string
                    description: |
                      A description of the error.
                required:
                  - error
                  - error_description
        '500':
          description: Internal Server Error
          content:
            application/json:
              examples:
                errorInvalidClient:
                  description: |
                    The service encountered an unrecoverable error when trying to access its internal resources
                  value:
                    {
                      "error": "server_error",
                      "error_description": "Server Error"
                    }
              schema:
                $ref: "#/components/schemas/InternalServerError"
      x-amazon-apigateway-integration:
        requestTemplates:
          application/json:
            statusCode: 200
        httpMethod: "POST"
        passthroughBehavior: "when_no_match"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AsyncTokenFunction}/invocations"
        type: "aws_proxy"
  /async/credential:
    post:
      summary: Submit a JAR to start a new DCMAW session
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                request:
                  type: string
                  example: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDg1NjYzMDcsImlhdCI6MTY0ODU2MjcwNywibmJmIjoxNjQ4NTYyNzA3LCJhdWQiOiJodHRwczovL2R3cC5nb3YudWsvIiwiaXNzIjoiaHR0cHM6Ly9pcHYuY29yZS5hY2NvdW50Lmdvdi51ayIsInN1YiI6InVybjpmZGM6Z292LnVrOjIwMjI6NTZQNENNc0doXzAyWU9sV3BkOFBBT0ktMnNWbEIybnNOVTdtY0xaWWhZdz0iLCJnb3Z1a19zaWduaW5fam91cm5leV9pZCI6IjQ0NDQ0NDQ0LTQ0NDQtNDQ0NC00NDQ0LTQ0NDQ0NDQ0NDQ0NCIsImNsaWVudF9pZCI6IkNMSUVOVF9JRCIsInN0YXRlIjoiUkFORE9NX1ZBTFVFIiwic2hhcmVkX2NsYWltcyI6eyJuYW1lIjpbeyJuYW1lUGFydHMiOlt7InZhbHVlIjoiQWxpY2UiLCJ0eXBlIjoiR2l2ZW5OYW1lIn0seyJ2YWx1ZSI6IkphbmUiLCJ0eXBlIjoiRmFtaWx5TmFtZSJ9XX1dLCJiaXJ0aERhdGUiOlt7InZhbHVlIjoiMTk3MC0wMS0wMSJ9XX19.ktFWVwPs_9AEsRU48hrKeQLBSxYW13DscODR81Tua__08Djwi-kXt1hca5PvcQllQg-qKVgmk_uRvAQwUc9epJ6_56SB8SHxTEGt2bmqwfrhwP30EOyyOfB9A9R6dolNVrJb_h_jPTiVaKF7_EX8R_wirTvkDmggSJFPRFE5kXRC2qHT0Hs_cciFz-cJnmFLhJTYyLDFkF33S6ycErRFrei2KOVeNprpeacXqKBFr7FAMuooxHyhK3TH2P9BvoE7AwgT2gumEjwnd19y_uabbXIWiJp6yiUwRce9P4cEkQevTl_JrkaCwmbJogkJJMsAIV_gSgjNrtOQgmQXFZpRXw
                  description: |
                    JWT-Secured Authorization Request (JAR)
              required:
                - request
      responses:
        '201':
          description: Created
          content:
            application/json:
              examples:
                success:
                  value:
                    {
                      "sub": "urn:fdc:gov.uk:2022:56P4CMsGh_02YOlWpd8PAOI-2sVlB2nsNU7mcLZYhYw=",
                      "https://vocab.account.gov.uk/v1/credentialStatus": "pending"
                    }
              schema:
                type: object
                properties:
                  sub:
                    type: string
                    description: |
                      The access token value is an access token represented as a DCMAW-signed JWT which you can use with DCMAW APIs
                  "https://vocab.account.gov.uk/v1/credentialStatus":
                    type: string
                    enum:
                      - pending
                    description: |
                      The status of the request at the time of creation.
                required:
                  - sub
                  - "https://vocab.account.gov.uk/v1/credentialStatus"
        '400':
          description: Bad request
          content:
            application/json:
              examples:
                errorInvalidRequest:
                  description: |
                    The request is missing a header or body so the server cannot proceed with the request.
                  value:
                    {
                      "error": "invalid_request",
                      "error_description": "Authorization header is missing"
                    }
              schema:
                $ref: "#/components/schemas/InternalServerError"
        '401':
          description: |
            Unauthorized, usually signifies the access_token is not valid
          content:
            application/json:
              examples:
                errorInvalidAccessToken:
                  description: |
                    Authentication failed, which could be caused by the request containing an invalid access token.
                  value:
                    {
                      "error": "invalid_token",
                      "error_description": "Invalid access token"
                    }
              schema:
                $ref: "#/components/schemas/Error"
        '500':
          description: Internal Server Error
          content:
            application/json:
              examples:
                internalServerError:
                  description: |
                    The server has encountered an unexpected condition or configuration problem that prevents 
                    it from fulfilling the request made by the browser or client.
                  value:
                    {
                      "error": "server_error",
                      "error_description": "Internal server error"
                    }
              schema:
                $ref: "#/components/schemas/InternalServerError"
      x-amazon-apigateway-integration:
        requestTemplates:
          application/json:
            statusCode: 200
        httpMethod: "POST"
        passthroughBehavior: "when_no_match"
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AsyncCredentialFunction}/invocations"
        type: "aws_proxy"