AWSTemplateFormatVersion: "2010-09-09"

Description: >-
  This configures DNS Query logging resources for the Route 53 service.
  - A CloudWatch LogGroup
  - AWS::Route53Resolver::ResolverQueryLoggingConfig to specify the config
  - AWS::Route53Resolver::ResolverQueryLoggingConfigAssociation to associate it with the VPC.

Parameters:
  Environment:
    Description: The name of the environment to deploy to
    Type: String
    AllowedValues:
      - dev 
      - build
      - staging
      - integration
      - production


Resources:
  QueryLoggingConfiguration:
    Type: AWS::Route53Resolver::ResolverQueryLoggingConfig
    Properties:
      DestinationArn: !GetAtt QueryLoggingLogGroup.Arn
      Name: DNSQueryLogging

  DnsQueryLogging:
    Type: AWS::Route53Resolver::ResolverQueryLoggingConfigAssociation
    Properties:
      ResolverQueryLogConfigId: !Ref QueryLoggingConfiguration
      ResourceId: !ImportValue devplatform-vpc-VpcId

  QueryLoggingLogGroup:
    # API Access Log not encrypted
    # checkov:skip=CKV_AWS_158: No PII in logs
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/${AWS::StackName}/${Environment}
      RetentionInDays: 30

Outputs:
  QueryLoggingConfId:
    Description: DNS Query Logging Configuration Id
    Value: !Ref QueryLoggingConfiguration
  QueryLoggingConfName:
    Description: DNS Query Logging Configuration Name
    Value: DNSQueryLogging
  QueryLoggingLogGroupName:
    Description: DNS Query Logging Group Name
    Value: !Ref QueryLoggingLogGroup