AWSTemplateFormatVersion: "2010-09-09"
Resources:
  VendorProcessingSqsOldMessageLowThresholdAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: DeployAlarms
    Properties:
      ActionsEnabled: true
      AlarmDescription: !Sub
        - "Trigger an alarm when the age of the oldest message in Vendor Processing SQS queue is 30 minutes or older. See runbook: ${RunbookUrl}"
        - RunbookUrl: !FindInMap [StaticVariables, urls, WarningAlarmsRunbook]
      AlarmName: !Sub "${AWS::StackName}-low-threshold-vendor-processing-sqs-old-message"
      AlarmActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-warning"
      OKActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-warning"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
      Threshold: 1800
      MetricName: ApproximateAgeOfOldestMessage
      Namespace: AWS/SQS
      Period: 60
      Statistic: Maximum
      Dimensions:
        - Name: QueueName
          Value: !GetAtt VendorProcessingSQS.QueueName

  VendorProcessingDlqNewMessageLowThresholdAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: DeployAlarms
    Properties:
      ActionsEnabled: true
      AlarmDescription: !Sub
        - "Trigger an alarm when new message gets added to Vendor Processing SQS DLQ. See runbook: ${RunbookUrl}"
        - RunbookUrl: !FindInMap [StaticVariables, urls, WarningAlarmsRunbook]
      AlarmName: !Sub "${AWS::StackName}-low-threshold-vendor-processing-dlq-new-message"
      AlarmActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-warning"
      OKActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-warning"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
      Threshold: 1
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Period: 60
      Statistic: Maximum
      Dimensions:
        - Name: QueueName
          Value: !GetAtt VendorProcessingDLQ.QueueName

  VendorProcessingDlqOldMessageLowThresholdAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: DeployAlarms
    Properties:
      ActionsEnabled: true
      AlarmDescription: !Sub
        - "Trigger an alarm when the age of the oldest message in Vendor Processing SQS DLQ is 3 days or older. See runbook: ${RunbookUrl}"
        - RunbookUrl: !FindInMap [StaticVariables, urls, WarningAlarmsRunbook]
      AlarmName: !Sub "${AWS::StackName}-low-threshold-vendor-processing-dlq-old-message"
      AlarmActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-warning"
      OKActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-warning"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
      Threshold: 259200
      MetricName: ApproximateAgeOfOldestMessage
      Namespace: AWS/SQS
      Period: 60
      Statistic: Maximum
      Dimensions:
        - Name: QueueName
          Value: !GetAtt VendorProcessingDLQ.QueueName

  VendorProcessingDlqOldMessageHighThresholdAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: DeployAlarms
    Properties:
      ActionsEnabled: true
      AlarmDescription: !Sub
        - "Trigger an alarm when the age of the oldest message in Vendor Processing SQS DLQ is 10 days or older. See runbook: ${RunbookUrl}"
        - RunbookUrl: !FindInMap [StaticVariables, urls, WarningAlarmsRunbook]
      AlarmName: !Sub "${AWS::StackName}-high-threshold-vendor-processing-dlq-old-message"
      AlarmActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-warning"
      OKActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-warning"
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
      Threshold: 864000
      MetricName: ApproximateAgeOfOldestMessage
      Namespace: AWS/SQS
      Period: 60
      Statistic: Maximum
      Dimensions:
        - Name: QueueName
          Value: !GetAtt VendorProcessingDLQ.QueueName