AWSTemplateFormatVersion: "2010-09-09"

Resources:
  AsyncAbortSessionThrottleAlarm:
    Condition: DeployAlarms
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: !Sub "${AWS::StackName}-abort-session-lambda-throttle"
      AlarmDescription: !Sub
        - "Trigger an alarm if the Async Abort Session Lambda throttles. See support manual: ${SupportManualUrl}"
        - SupportManualUrl: !FindInMap [StaticVariables, urls, SupportManual]
      AlarmActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-critical"
      OKActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-critical"
      InsufficientDataActions: []
      Namespace: AWS/Lambda
      MetricName: Throttles
      Dimensions:
        - Name: FunctionName
          Value: !Ref AsyncAbortSessionFunction
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Period: 60
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      TreatMissingData: notBreaching

  AsyncActiveSessionThrottleAlarm:
    Condition: DeployAlarms
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: !Sub "${AWS::StackName}-active-session-lambda-throttle"
      AlarmDescription: !Sub
        - "Trigger an alarm if the Async Active Session Lambda throttles. See support manual: ${SupportManualUrl}"
        - SupportManualUrl: !FindInMap [StaticVariables, urls, SupportManual]
      AlarmActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-critical"
      OKActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-critical"
      InsufficientDataActions: []
      Namespace: AWS/Lambda
      MetricName: Throttles
      Dimensions:
        - Name: FunctionName
          Value: !Ref AsyncActiveSessionFunction
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Period: 60
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      TreatMissingData: notBreaching

  AsyncBiometricTokenThrottleAlarm:
    Condition: DeployAlarms
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: !Sub "${AWS::StackName}-biometric-token-lambda-throttle"
      AlarmDescription: !Sub
        - "Trigger an alarm if the Async Biometric Token Lambda throttles. See support manual: ${SupportManualUrl}"
        - SupportManualUrl: !FindInMap [StaticVariables, urls, SupportManual]
      AlarmActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-critical"
      OKActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-critical"
      InsufficientDataActions: []
      Namespace: AWS/Lambda
      MetricName: Throttles
      Dimensions:
        - Name: FunctionName
          Value: !Ref AsyncBiometricTokenFunction
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Period: 60
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      TreatMissingData: notBreaching

  AsyncCredentialThrottleAlarm:
    Condition: DeployAlarms
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: !Sub "${AWS::StackName}-credential-lambda-throttle"
      AlarmDescription: !Sub
        - "Trigger an alarm if the Async Credential Lambda throttles. See support manual: ${SupportManualUrl}"
        - SupportManualUrl: !FindInMap [StaticVariables, urls, SupportManual]
      AlarmActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-critical"
      OKActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-critical"
      InsufficientDataActions: []
      Namespace: AWS/Lambda
      MetricName: Throttles
      Dimensions:
        - Name: FunctionName
          Value: !Ref AsyncCredentialFunction
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Period: 60
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      TreatMissingData: notBreaching

  AsyncFinishBiometricSessionThrottleAlarm:
    Condition: DeployAlarms
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: !Sub "${AWS::StackName}-finish-biometric-session-lambda-throttle"
      AlarmDescription: !Sub
        - "Trigger an alarm if the Async Finish Biometric Session Lambda throttles. See support manual: ${SupportManualUrl}"
        - SupportManualUrl: !FindInMap [StaticVariables, urls, SupportManual]
      AlarmActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-critical"
      OKActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-critical"
      InsufficientDataActions: []
      Namespace: AWS/Lambda
      MetricName: Throttles
      Dimensions:
        - Name: FunctionName
          Value: !Ref AsyncFinishBiometricSessionFunction
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Period: 60
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      TreatMissingData: notBreaching

  AsyncTokenThrottleAlarm:
    Condition: DeployAlarms
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: !Sub "${AWS::StackName}-token-lambda-throttle"
      AlarmDescription: !Sub
        - "Trigger an alarm if the Async Token Lambda throttles. See support manual: ${SupportManualUrl}"
        - SupportManualUrl: !FindInMap [StaticVariables, urls, SupportManual]
      AlarmActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-critical"
      OKActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-critical"
      InsufficientDataActions: []
      Namespace: AWS/Lambda
      MetricName: Throttles
      Dimensions:
        - Name: FunctionName
          Value: !Ref AsyncTokenFunction
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Period: 60
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      TreatMissingData: notBreaching

  AsyncTxmaEventThrottleAlarm:
    Condition: DeployAlarms
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: !Sub "${AWS::StackName}-txma-event-lambda-throttle"
      AlarmDescription: !Sub
        - "Trigger an alarm if the Async TxMA Event Lambda throttles. See support manual: ${SupportManualUrl}"
        - SupportManualUrl: !FindInMap [StaticVariables, urls, SupportManual]
      AlarmActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-critical"
      OKActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-critical"
      InsufficientDataActions: []
      Namespace: AWS/Lambda
      MetricName: Throttles
      Dimensions:
        - Name: FunctionName
          Value: !Ref AsyncTxmaEventFunction
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Period: 60
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      TreatMissingData: notBreaching

  ProxyLambdaThrottleAlarm:
    Condition: DeployProxyAlarms
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmName: !Sub "${AWS::StackName}-proxy-lambda-throttle"
      AlarmDescription: !Sub
        - "Trigger an alarm if the Proxy Lambda throttles. See runbook: ${RunbookUrl}"
        - RunbookUrl: !FindInMap [StaticVariables, urls, WarningAlarmsRunbook]
      AlarmActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-warning"
      OKActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:platform-alarms-sns-warning"
      InsufficientDataActions: []
      Namespace: AWS/Lambda
      MetricName: Throttles
      Dimensions:
        - Name: FunctionName
          Value: !Ref ProxyLambda
      Statistic: Sum
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Period: 60
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
