AWSTemplateFormatVersion: "2010-09-09"

Resources:
  JwksBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-sts-mock-jwks-${Environment}
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Ref JwksBucketAccessLogs
        LogFilePrefix: !Sub ${AWS::StackName}-sts-mock-jwks

  JwksBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref JwksBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Deny
            Principal:
              AWS: "*"
            Action: "*"
            Resource: !Sub
              - arn:aws:s3:::${TargetBucket}/*
              - TargetBucket: !Ref JwksBucket
            Condition:
              Bool:
                "aws:SecureTransport": false

  JwksBucketAccessLogs:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-sts-mock-jwks-access-logs-${Environment}
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter

  JwksBucketAccessLogsPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref JwksBucketAccessLogs
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Deny
            Principal:
              AWS: "*"
            Action: "*"
            Resource: !Sub
              - arn:aws:s3:::${bucketName}/*
              - bucketName: !Ref JwksBucketAccessLogs
            Condition:
              Bool:
                "aws:SecureTransport": false
          - Effect: Allow
            Principal:
              Service: logging.s3.amazonaws.com
            Action:
              - s3:PutObject
            Resource: !Sub
              - arn:aws:s3:::${bucketName}/*
              - bucketName: !Ref JwksBucketAccessLogs
            Condition:
              ArnLike:
                aws:SourceArn: !GetAtt JwksBucket.Arn
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
