AWSTemplateFormatVersion: "2010-09-09"

Description: |
  Creates the IAM roles and policies needed for mobile app developers to test in AWS

Parameters:
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - dev
      - build
    Default: dev

Conditions:
  IsBuild:
    Fn::Equals:
      - !Ref Environment
      - build

  IsDevOrBuild: !Or
    - !Equals
      - !Ref Environment
      - dev
    - !Equals
      - !Ref Environment
      - build

Resources:
  MobAppPolicy:
    Condition: IsDevOrBuild
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: mob-app
      Description: "Policy to allow invoking Proxy API Gateway and to retrieve secrets."
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "InvokeProxyApiGateway"
            Effect: "Allow"
            Action:
              - "execute-api:Invoke"
            Resource:
                - !Sub 
                  - "${PROXYAPIEXECUTEARN}/POST/async/token"
                  - PROXYAPIEXECUTEARN: !ImportValue mob-async-backend-proxy-api-execute-arn
                - !Sub 
                  - "${PROXYAPIEXECUTEARN}/POST/async/credentials"
                  - PROXYAPIEXECUTEARN: !ImportValue mob-async-backend-proxy-api-execute-arn
          - Sid: "GetSecrets"
            Effect: "Allow"
            Action:
              - "secretsmanager:GetSecretValue"
            Resource:
              - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${Environment}/clientRegistryMobileAppCredentials-??????"

  MobAppGitHubActionsRole:
    Condition: IsBuild
    Type: AWS::IAM::Role
    Properties:
      RoleName: "mob-app-github-actions"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRoleWithWebIdentity"
            Principal:
              Federated: !ImportValue GitHubIdentityProviderArn
            Condition:
              StringLike:
                "token.actions.githubusercontent.com:sub":
                  - "repo:govuk-one-login/mobile-android-cri-orchestrator:ref:refs/heads/*"
                  - "repo:govuk-one-login/mobile-id-check-ios-sdk:ref:refs/heads/*"
      ManagedPolicyArns:
        - !Ref MobAppPolicy
      Tags:
        - Key: "Name"
          Value: "mob-app-github-actions"
        - Key: "Source"
          Value: "govuk-one-login/mobile-id-check-async/infra/templates/iam/template.yaml"