AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Description: The environment type
  PermissionsBoundary:
    Type: String
    Description: The ARN of the permissions boundary
  StackName:
    Type: String
    Description: Name of the parent stack
  PrivateApiId:
    Type: String
    Description: ID of the private API Gateway
  KmsSigningKeyArn:
    Type: String
    Description: ARN of the KMS signing key
  TxMAQueueArn:
    Type: String
    Description: ARN of the TxMA SQS queue
  TxMAKmsKeyArn:
    Type: String
    Description: ARN of the TxMA KMS key

Resources:
  AsyncTokenFunction:
    Type: AWS::Serverless::Function
    DependsOn:
      - AsyncTokenLogGroup
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: false
        EntryPoints:
          - src/functions/asyncToken/asyncTokenHandler.ts
    Properties:
      FunctionName: !Sub ${StackName}-token
      Runtime: nodejs20.x
      Handler: asyncTokenHandler.lambdaHandler
      Role: !GetAtt AsyncTokenLambdaRole.Arn
      Environment:
        Variables:
          CLIENT_REGISTRY_SECRET_NAME: !Sub ${Environment}/clientRegistry
      VpcConfig:
        SubnetIds:
          - !ImportValue devplatform-vpc-PrivateSubnetIdA
          - !ImportValue devplatform-vpc-PrivateSubnetIdB
          - !ImportValue devplatform-vpc-PrivateSubnetIdC
        SecurityGroupIds:
          - !ImportValue devplatform-vpc-AWSServicesEndpointSecurityGroupId

  AsyncTokenFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt AsyncTokenFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceAccount: !Sub ${AWS::AccountId}
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PrivateApiId}/*/*/*

  AsyncTokenLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 30
      LogGroupName: !Sub /aws/lambda/${StackName}-token

  AsyncTokenLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${StackName}-token-lambda
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AsyncTokenFunctionSecretsManagerPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${Environment}/clientRegistry-??????
        - PolicyName: AsyncTokenFunctionLoggingPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
        - PolicyName: AsyncTokenFunctionKmsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - kms:Sign
                Resource: !Ref KmsSigningKeyArn
        - PolicyName: AsyncTokenFunctionSQSPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !Ref TxMAQueueArn
              - Effect: Allow
                Action:
                  - kms:Encrypt
                  - kms:Decrypt
                  - kms:GenerateDataKey
                Resource: !Ref TxMAKmsKeyArn
        - PolicyName: VpcPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeNetworkInterfaces
                  - ec2:CreateNetworkInterface
                  - ec2:DeleteNetworkInterface
                Resource: '*'
      PermissionsBoundary: !Ref PermissionsBoundary

Outputs:
  FunctionArn:
    Description: Token Lambda Function ARN
    Value: !GetAtt AsyncTokenFunction.Arn
  
  FunctionName:
    Description: Token Lambda Function Name
    Value: !Ref AsyncTokenFunction