AWSTemplateFormatVersion: "2010-09-09"

Description: |
  Creates the IAM roles and policies needed for App Devs to test in AWS

Parameters:
  Environment:
    Description: The environment type
    Type: String
    AllowedValues:
      - dev
    Default: dev

Conditions:
  Isdev:
    - !Equals
      - !Ref Environment
      - dev

Resources:
  AppDevsGitHubActionsPolicy:
    Condition: IsDev
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: mob-app-dev-github-actions
      Description: "Policy to allow GitHub actions to retrieve secrets."
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "InvokeProxyApiGateway"
            Effect: "Allow"
            Action:
              - "apigateway:POST"
            Resource: "arn:aws:apigateway:eu-west-2::/domainnames/proxy-mob-async-backend.review-b-async.dev.account.gov.uk/dev/*"
          - Sid: "GetSecrets"
            Effect: "Allow"
            Action:
              - "secretsmanager:GetSecretValue"
            Resource: "dev/clientRegistryMobileAppCredentials"

  AppDevsGitHubActionsRole:
    Condition: IsDev
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRoleWithWebIdentity"
            Principal:
              Federated: !ImportValue GitHubIdentityProviderArn
            Condition:
              StringLike:
                "token.actions.githubusercontent.com:sub":
                  - "repo:govuk-one-login/mobile-android-cri-orchestrator:ref:refs/heads/*",
                  - "repo:govuk-one-login/mobile-id-check-ios-sdk:ref:refs/heads/*",
      ManagedPolicyArns:
        - !Ref AppDevsGitHubActionsPolicy
      Tags:
        - Key: "Name"
          Value: "mob-app-dev-github-actions"
        - Key: "Service"
          Value: "ci/cd"
        - Key: "Source"
          Value: "govuk-one-login/devplatform-deploy/sam-deploy-pipeline/template.yaml"