AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Description: The environment type
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - build

  PermissionsBoundary:
    Description: |
      The ARN of the permissions boundary to apply to any role created by the template
    Type: String
    Default: none

  BackendApi:
    Description: The Stack name of the Async Backend stack
    Type: String
    Default: mob-async-backend

Conditions:
  UsePermissionsBoundary: !Not
    - !Equals
      - !Ref PermissionsBoundary
      - none

  IsDevOrBuild: !Or
    - !Equals
      - !Ref Environment
      - dev
    - !Equals
      - !Ref Environment
      - build

Mappings:
  EnvironmentVariables:
    dev:
      TXMAEVENTTTLINSECONDS: 3600
    build:
      TXMAEVENTTTLINSECONDS: 3600

Resources:
  # Dequeue resources
  DequeueFunction:
    Type: AWS::Serverless::Function
    Condition: IsDevOrBuild
    DependsOn:
      - DequeueLogGroup
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        Sourcemap: false
        EntryPoints:
          - src/dequeue/dequeueHandler.ts
    Properties:
      FunctionName: !Sub ${AWS::StackName}-dequeue
      Runtime: nodejs20.x
      Handler: dequeueHandler.lambdaHandler
      Role: !GetAtt DequeueRole.Arn
      Environment:
        Variables:
          TXMA_EVENT_TTL_IN_SECONDS: !FindInMap
            - EnvironmentVariables
            - !Ref Environment
            - TXMAEVENTTTLINSECONDS
      Timeout: 10
      VpcConfig:
        SubnetIds:
          - !ImportValue devplatform-vpc-PrivateSubnetIdA
          - !ImportValue devplatform-vpc-PrivateSubnetIdB
          - !ImportValue devplatform-vpc-PrivateSubnetIdC
        SecurityGroupIds:
          - !ImportValue devplatform-vpc-AWSServicesEndpointSecurityGroupId

  DequeueLogGroup:
    Type: AWS::Logs::LogGroup
    Condition: IsDevOrBuild
    Properties:
      RetentionInDays: 30
      LogGroupName: !Sub /aws/lambda/${AWS::StackName}-dequeue

  DequeueRole:
    Type: AWS::IAM::Role
    Condition: IsDevOrBuild
    Properties:
      RoleName: !Sub ${AWS::StackName}-dequeue-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LoggingPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
        - PolicyName: SQSPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource:
                  Fn::ImportValue: !Sub ${BackendApi}-txma-sqs-queue-arn
        - PolicyName: DynamoDBPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:BatchWriteItem
                Resource: !GetAtt DequeueTable.Arn
        - PolicyName: KMSPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource:
                  Fn::ImportValue: !Sub ${BackendApi}-txma-kms-encryption-key-arn
        - PolicyName: VpcPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeNetworkInterfaces
                  - ec2:CreateNetworkInterface
                  - ec2:DeleteNetworkInterface
                Resource: '*'
      PermissionsBoundary: !If
        - UsePermissionsBoundary
        - !Ref PermissionsBoundary
        - !Ref AWS::NoValue

  DequeueEventSourceMapping:
    Condition: IsDevOrBuild
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn:
        Fn::ImportValue: !Sub ${BackendApi}-txma-sqs-queue-arn
      FunctionName: !GetAtt DequeueFunction.Arn
      FunctionResponseTypes:
        - ReportBatchItemFailures

  DequeueTable:
    Type: AWS::DynamoDB::Table
    Condition: IsDevOrBuild
    Properties:
      TableName: !Sub ${AWS::StackName}-dequeue-table
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      TimeToLiveSpecification:
        AttributeName: timeToLive
        Enabled: true
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
