name: Async-credential Pull Request CI
on:
  # Triggers the workflow on pull request events for all branches
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
    paths:
      - "./src/**"
      - ".github/workflows/async-credential-pull-req.yml"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SIGNING_KEY_IDS: "test"

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup nodeJS v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: src/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run tests #This should be updated to only run unit/infra tests when they have been categorised as such
        run: npm run test