name: Async-credential Push to Main
on:
  push:
    branches:
      - main
    paths:
      - "backend-api/**"
      - ".github/workflows/backend-api-push-to-main.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sonar-scan:
    name: Sonar main branch scan
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend-api
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup nodeJS v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend-api/package-lock.json

      - name: Install dependencies
        run: npm install

      # Generate test coverage report for Sonar main branch analysis
      - name: Run Tests
        run: npm run test:unit

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.javascript.lcov.reportPaths=./backend-api/coverage/lcov.info
