name: Build, Sign, Push and Tag test image

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        required: true
        type: string
    secrets:
      GH_ACTIONS_ROLE_ARN:
        required: true
      TEST_IMAGE_REPOSITOR_URI:
        required: true
      CONTAINER_SIGN_KMS_KEY:
        required: true

jobs:
  build-and-push:
    name: build-and-push
    runs-on: ubuntu-24.04
    env:
      IMAGE_TAG: latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Cosign
        uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da #v3.7.0
        with:
          cosign-release: 'v1.9.0'

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 #v4.0.2
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 #v2.0.1

      - name: Build image
        run: |
          docker build -t ${{ secrets.TEST_IMAGE_REPOSITOR_URI }}:$IMAGE_TAG . 

      - name: Push image
        run: |
          docker push ${{ secrets.TEST_IMAGE_REPOSITOR_URI }}:$IMAGE_TAG

      - name: Sign image
        run: |
          cosign sign --key awskms:///${{ secrets.CONTAINER_SIGN_KMS_KEY }} ${{ secrets.TEST_IMAGE_REPOSITOR_URI }}:$IMAGE_TAG
