name: Build, Sign, Push and Tag test image

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        required: true
        type: string

jobs:
  build-and-push-image:
    name: build-and-push-image
    runs-on: ubuntu-24.04
    env:
      IMAGE_TAG: latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
          fetch-depth: 0

      - name: test script
        run: |
          echo "we're in job_build-and-push-test-image workflow"

      # - name: Install Cosign
      #   uses: sigstore/cosign-installer@c56c2d3e59e4281cc41dea2217323ba5694b171e # v3.8.0
      #   with:
      #     cosign-release: 'v1.9.0'

      # - name: Authenticate with AWS
      #   uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
      #   with:
      #     aws-region: eu-west-2
      #     role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}

      # - name: Login to AWS ECR
      #   uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      # - name: Build image
      #   run: |
      #     docker build -t ${{ secrets.TEST_IMAGE_REPOSITORY_URI }}:$IMAGE_TAG . 

      # - name: Push image
      #   run: |
      #     docker push ${{ secrets.TEST_IMAGE_REPOSITORY_URI }}:$IMAGE_TAG

      # - name: Sign image
      #   run: |
      #     cosign sign --key awskms:///${{ secrets.CONTAINER_SIGN_KMS_KEY }} ${{ secrets.TEST_IMAGE_REPOSITORY_URI }}:$IMAGE_TAG