name: Release ci-checks
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/jobs_ci-checks.yml"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: read

defaults:
  run:
    shell: bash

jobs:
  create-tag:
    name: Create Tag
    runs-on: ubuntu-24.04
    env:
      SAM_CLI_TELEMETRY: 0
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
      
      - name: Get version
        run: |
          pwd
