name: sts-mock pull request
on:
  # Triggers the workflow on pull request events for all branches
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
    paths:
      - "sts-mock/**"
      - ".github/workflows/sts-mock-pull-request.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ci-checks:
    name: Run CI checks
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: sts-mock
    steps:
      - name: Check out repository code
        uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 #main
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup nodeJS v20
        uses: actions/setup-node@26961cf329f22f6837d5f54c3efd76b480300ace #main
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: sts-mock/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Check formatting using Prettier
        run: npm run format:check

      # Runs unit and infrastructure tests
      - name: Run tests 
        run: npm run test

      - name: Run SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@f5003fc9688ade81ce47b57a3fa97a8d3f12de4c #master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.javascript.lcov.reportPaths=./sts-mock/coverage/lcov.info

      - name: SonarQube Quality Gate check
        uses: Sonarsource/sonarqube-quality-gate-action@72f24ebf1f81eda168a979ce14b8203273b7c3ad #master
        # Force to fail step after specific time
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}