name: Test Resources Post Merge
on:
  push:
    branches:
      - main
    paths:
      - "test-resources/**"
      - ".github/workflows/test-resources-post-merge.yml"
      - "!test-resources/**/*.md"
      - "!test-resources/**/*.png"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash
    working-directory: test-resources

jobs:
  # pre-merge-checks:
  #   name: Pre-merge checks
  #   uses:
  #     ./.github/workflows/workflow_pull-request.yml
  #   with:
  #     WORKING_DIRECTORY: test-resources
  #   secrets: inherit

  build-and-push-test-image-dev:
    name: Dev
    # needs: pre-merge-checks
    uses:
      ./.github/jobs/build-and-push-test-image/build-and-push-test-image.yaml
    with:
      WORKING_DIRECTORY: test-resources
    secrets:
      CONTAINER_SIGN_KMS_KEY: ${{ secrets.DEV_CONTAINER_SIGN_KMS_KEY }}
      GH_ACTIONS_ROLE_ARN: ${{ secrets.TEST_RESOURCES_DEV_GH_ACTIONS_ROLE_ARN }}
      TEST_IMAGE_REPOSITOR_URI: ${{ secrets.TEST_RESOURCES_DEV_TEST_IMAGE_REPOSITORY_URI }}

  validate-and-upload-artifact-to-s3-dev:
    name: Dev
    needs: build-and-push-test-image-dev
    uses:
      ./.github/jobs/validate-and-upload-artifact/validate-and-upload-artifact.yaml
    with:
      WORKING_DIRECTORY: test-resources
    secrets:
      ARTIFACT_BUCKET: ${{ secrets.TEST_RESOURCES_DEV_ARTIFACT_BUCKET }}
      GH_ACTIONS_ROLE_ARN: ${{ secrets.TEST_RESOURCES_DEV_GH_ACTIONS_ROLE_ARN }}
      SIGNING_PROFILE_NAME: ${{ secrets.DEV_SIGNING_PROFILE_NAME }}

  build-and-push-test-image-build:
    name: Build
    # needs: pre-merge-checks
    uses:
      ./.github/jobs/build-and-push-test-image/build-and-push-test-image.yaml
    with:
      WORKING_DIRECTORY: test-resources
    secrets:
      CONTAINER_SIGN_KMS_KEY: ${{ secrets.BUILD_CONTAINER_SIGN_KMS_KEY }}
      GH_ACTIONS_ROLE_ARN: ${{ secrets.TEST_RESOURCES_BUILD_GH_ACTIONS_ROLE_ARN }}
      TEST_IMAGE_REPOSITOR_URI: ${{ secrets.TEST_RESOURCES_BUILD_TEST_IMAGE_REPOSITORY_URI }}

  validate-and-upload-artifact-to-s3-build:
    name: Build
    needs: build-and-push-test-image-build
    uses:
      ./.github/jobs/validate-and-upload-artifact/validate-and-upload-artifact.yaml
    with:
      WORKING_DIRECTORY: test-resources
    secrets:
      ARTIFACT_BUCKET: ${{ secrets.TEST_RESOURCES_BUILD_ARTIFACT_BUCKET }}
      GH_ACTIONS_ROLE_ARN: ${{ secrets.TEST_RESOURCES_BUILD_GH_ACTIONS_ROLE_ARN }}
      SIGNING_PROFILE_NAME: ${{ secrets.BUILD_SIGNING_PROFILE_NAME }}
