name: test-resources push to main
on:
  push:
    branches:
      - main
    paths:
      - "test-resources/**"
      - ".github/workflows/test-resources-push-to-main.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  sonar-scan:
    name: Sonar main branch scan
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: test-resources
    steps:
      - name: Check out repository code
        uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 #main
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup nodeJS v20
        uses: actions/setup-node@26961cf329f22f6837d5f54c3efd76b480300ace #main
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: test-resources/package-lock.json

      - name: Install dependencies
        run: npm install

      # Generate test coverage report for Sonar main branch analysis
      - name: Run Tests
        run: npm run test:unit

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@02ef91109b2d589e757aefcfb2854c2783fd7b19 #master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: test-resources
