name: Post-Merge Workflow Failure

on:
  workflow_run:
    workflows:
      - "Backend API Post Merge"
      - "Test Resources Post Merge"
    types:
      - completed
    branches:
      - main

permissions:
  contents: read

jobs:
  error-handler:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-24.04
    steps:
      - name: Notify on failure
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        with:
          webhook-type: webhook-trigger
          webhook: ${{ secrets.SLACK_WEBHOOK_BACKEND_DEV }}
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":x: Github Workflow Failure:  ${{ github.event.workflow.name }} :x:"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Title*: ${{ github.event.workflow_run.display_title }}\n*Workflow*: ${{ github.event.workflow_run.html_url }}\n*Branch*: ${{ github.event.workflow_run.head_branch }}\n"
                    },
                  ]
                }
              ]
            }
