name: Post merge - runs tests, sonarQube, and deploys to dev and build

on:
  workflow_call:
    inputs:
      RUN_SONARQUBE_SCAN:
        description: Whether to run sonarQube scans
        required: false
        type: boolean
        default: false
      WORKING_DIRECTORY:
        description: Working directory
        required: true
        type: string
    secrets:
      DEV_ARTIFACT_BUCKET_NAME:
        description: Dev Artifact source bucket for SAM artifact
        required: true
      DEV_CONTAINER_SIGN_KMS_KEY:
        description: Dev AWS Role for pushing the test image and AWS artifact to AWS
        required: true
      DEV_GH_ACTIONS_ROLE_ARN:
        description: Dev uri of the ECR for the test images
        required: true
      DEV_SIGNING_PROFILE_NAME: 
        description: Dev Profile used to sign SAM artifact
        required: true
      DEV_TEST_IMAGE_REPOSITORY_URI: 
        description: Dev KMS key for encrypting the test image
        required: true
      BUILD_ARTIFACT_BUCKET_NAME:
        description: Build Artifact source bucket for SAM artifact
        required: true
      BUILD_CONTAINER_SIGN_KMS_KEY:
        description: Build AWS Role for pushing the test image and AWS artifact to AWS
        required: true
      BUILD_GH_ACTIONS_ROLE_ARN:
        description: Build uri of the ECR for the test images
        required: true
      BUILD_SIGNING_PROFILE_NAME: 
        description: Build Profile used to sign SAM artifact
        required: true
      BUILD_TEST_IMAGE_REPOSITORY_URI: 
        description: Build KMS key for encrypting the test image
        required: true

jobs:
  run-test-suite:
    name: Run test suite
    uses:
      govuk-one-login/mobile-id-check-async/.github/workflows/job_test-suite.yml@DCMAW-11654
    with:
      RUN_SONARQUBE_SCAN: ${{ inputs.RUN_SONARQUBE_SCAN }}
      WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}

  sonarqube-scan:
    name: SonarQube Scan
    if: ${{ inputs.RUN_SONARQUBE_SCAN }}
    needs: run-test-suite
    uses:
      govuk-one-login/mobile-id-check-async/.github/workflows/job_sonarqube.yml@DCMAW-11654
    with:
      DOWNLOAD_TEST_COVERAGE: true
      RUN_SONARQUBE_QUALITY_GATE_CHECK: false
      WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
    secrets: inherit

  dev-build-and-push-image:
    name: Dev - build and push test image
    needs: run-test-suite
    uses:
      govuk-one-login/mobile-id-check-async/.github/workflows/job_build-and-push-test-image.yml@DCMAW-11654
    with:
      WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
    secrets:
      CONTAINER_SIGN_KMS_KEY: ${{ secrets.DEV_CONTAINER_SIGN_KMS_KEY }}
      GH_ACTIONS_ROLE_ARN: ${{ secrets.DEV_GH_ACTIONS_ROLE_ARN }}
      TEST_IMAGE_REPOSITORY_URI: ${{ secrets.DEV_TEST_IMAGE_REPOSITORY_URI }}

  dev-build-and-upload-sam-artifact:
    name: Dev - build and upload SAM artifact to S3 bucket
    needs: dev-build-and-push-image
    uses:
      govuk-one-login/mobile-id-check-async/.github/workflows/job_build-and-upload-sam-app.yml@DCMAW-11654
    with:
      WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
    secrets:
      ARTIFACT_BUCKET_NAME: ${{ secrets.DEV_ARTIFACT_BUCKET_NAME }}
      CONTAINER_SIGN_KMS_KEY: ${{ secrets.DEV_CONTAINER_SIGN_KMS_KEY }}
      GH_ACTIONS_ROLE_ARN: ${{ secrets.DEV_GH_ACTIONS_ROLE_ARN }}
      SIGNING_PROFILE_NAME: ${{ secrets.DEV_SIGNING_PROFILE_NAME }}

  build-build-and-push-image:
    name: Build - build and push test image
    needs: run-test-suite
    uses:
      govuk-one-login/mobile-id-check-async/.github/workflows/job_build-and-push-test-image.yml@DCMAW-11654
    with:
      WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
    secrets:
      CONTAINER_SIGN_KMS_KEY: ${{ secrets.BUILD_CONTAINER_SIGN_KMS_KEY }}
      GH_ACTIONS_ROLE_ARN: ${{ secrets.BUILD_GH_ACTIONS_ROLE_ARN }}
      TEST_IMAGE_REPOSITORY_URI: ${{ secrets.BUILD_TEST_IMAGE_REPOSITORY_URI }}

  build-build-and-upload-sam-artifact:
    name: Build - build and upload SAM artifact to S3 bucket
    needs: build-build-and-push-image
    uses:
      govuk-one-login/mobile-id-check-async/.github/workflows/job_build-and-upload-sam-app.yml@DCMAW-11654
    with:
      WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
    secrets:
      ARTIFACT_BUCKET_NAME: ${{ secrets.BUILD_ARTIFACT_BUCKET_NAME }}
      CONTAINER_SIGN_KMS_KEY: ${{ secrets.BUILD_CONTAINER_SIGN_KMS_KEY }}
      GH_ACTIONS_ROLE_ARN: ${{ secrets.BUILD_GH_ACTIONS_ROLE_ARN }}
      SIGNING_PROFILE_NAME: ${{ secrets.BUILD_SIGNING_PROFILE_NAME }}